---
name: Publish Markdown on Confluence
description: Recursively converts markdown files in a GitHub project into a series of pages and sub-pages on Confluence
author: Ari Kalfus <dev@artis3nal.com>
inputs:
  confluence_url:
    description: |
      The hostname of the Confluence server.

      For Confluence Cloud, this is https://<subdomain>.atlassian.net/wiki.

      NOTE the /wiki in the URL. For Confluence Cloud, you must specify this, or the alternative URI at which your Confluence instance resides.

      For Confluence Server, this is https://<your hostname>:8090.

      NOTE that you should modify this hostname as appropriate for your Server instance.
      For example, it is unlikely that you are directly accessing port 8090, and are instead proxied through 80 or 443, which only requires http:// or https://.
    required: true
  space_key:
    description: |
      The space key for your Space on Confluence.

      On Confluence Cloud, you can usually find this in the URL inside your space in the format: https://<subdomain>.atlassian.net/wiki/spaces/<SPACEKEY>/.

      On Confluence Server, you can usually find this in the URL inside your space in the format: https://<your_domain>/display/<SPACEKEY>/.

      The space key is an alphanumeric string up to 255 characters long. The default generated by Confluence is 2 characters.
    required: true
  username:
    description: The username with which to authenticate to Confluence.
    required: true
  password:
    description: The API token or password with which to authenticate to Confluence.
    required: true
  base_url:
    description: |
      A base URL to convert any relative links found in the markdown.

      If not provided, the Action will use the current repository and default branch, e.g. https://github.com/<repo_owner>/<repo_name>/blob/<REF>/, where <REF> is the current ref in the GitHub Action context.
      This is typically the branch from which the Action workflow is running (a branch if inside a PR, main/master if run upon a push to the default branch).

      e.g. https://github.com/artis3n/markdown-to-confluence/blob/main/
    required: false
  docs_path:
    description: |
      Relative path in the GitHub repository from which markdown files should be discovered and converted.

      Defaults to the repo root.
    required: false
    default: './'
  debug_mode:
    description: |
      Enable debug mode, which prints out verbose information about the wiki conversion process.
      Useful to debug connectivity issues between the GitHub Action and your Confluence instance.

      Options: [true, false] (strings)

      Default: false
    required: false
    default: 'false'
  code_theme:
    description: |
      What Confluence code theme to apply to code blocks. Must be a valid Confluence code block theme.

      Options: [Confluence, DJango, Emacs, FadeToGrey, Midnight, RDark, Eclipse]

      Default: Confluence
    required: false
    default: 'Confluence'
  code_line_numbers:
    description: |
      Whether to include line numbers in code blocks.

      Options: [true, false] (strings)

      Default: true
    required: false
    default: 'true'
runs:
  using: docker
  image: Dockerfile
branding:
  icon: briefcase
  color: blue
